/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard/students'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardFeedbacksRouteImport } from './routes/dashboard/feedbacks'
import { Route as DashboardComplaintsRouteImport } from './routes/dashboard/complaints'
import { Route as DashboardAdminsRouteImport } from './routes/dashboard/admins'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeedbacksRoute = DashboardFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplaintsRoute = DashboardComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminsRoute = DashboardAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/admins': typeof DashboardAdminsRoute
  '/dashboard/complaints': typeof DashboardComplaintsRoute
  '/dashboard/feedbacks': typeof DashboardFeedbacksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/signup': typeof SignupRoute
  '/dashboard/admins': typeof DashboardAdminsRoute
  '/dashboard/complaints': typeof DashboardComplaintsRoute
  '/dashboard/feedbacks': typeof DashboardFeedbacksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/admins': typeof DashboardAdminsRoute
  '/dashboard/complaints': typeof DashboardComplaintsRoute
  '/dashboard/feedbacks': typeof DashboardFeedbacksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/signup'
    | '/dashboard/admins'
    | '/dashboard/complaints'
    | '/dashboard/feedbacks'
    | '/dashboard/profile'
    | '/dashboard/students'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/signup'
    | '/dashboard/admins'
    | '/dashboard/complaints'
    | '/dashboard/feedbacks'
    | '/dashboard/profile'
    | '/dashboard/students'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/signup'
    | '/dashboard/admins'
    | '/dashboard/complaints'
    | '/dashboard/feedbacks'
    | '/dashboard/profile'
    | '/dashboard/students'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/feedbacks': {
      id: '/dashboard/feedbacks'
      path: '/feedbacks'
      fullPath: '/dashboard/feedbacks'
      preLoaderRoute: typeof DashboardFeedbacksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/complaints': {
      id: '/dashboard/complaints'
      path: '/complaints'
      fullPath: '/dashboard/complaints'
      preLoaderRoute: typeof DashboardComplaintsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admins': {
      id: '/dashboard/admins'
      path: '/admins'
      fullPath: '/dashboard/admins'
      preLoaderRoute: typeof DashboardAdminsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminsRoute: typeof DashboardAdminsRoute
  DashboardComplaintsRoute: typeof DashboardComplaintsRoute
  DashboardFeedbacksRoute: typeof DashboardFeedbacksRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminsRoute: DashboardAdminsRoute,
  DashboardComplaintsRoute: DashboardComplaintsRoute,
  DashboardFeedbacksRoute: DashboardFeedbacksRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
